CREATE TABLE Version
(
	Id INT PRIMARY KEY IDENTITY,
	VersionNumber VARCHAR(30) NOT NULL,
	CreateDate DATETIME2
)
GO

CREATE TABLE Drink
(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(60) NOT NULL
)
GO

CREATE TABLE Ingredient
(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(60) NOT NULL,
	DrinkId INT CONSTRAINT FK_Ingredient_Drink FOREIGN KEY (DrinkId) REFERENCES Drink(Id)
)

INSERT INTO Version(VersionNumber, CreateDate) VALUES ('0.0.0.1', GETDATE())